/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.ClienteDAO;
import classes.Cliente;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mauricio
 */
public class ClienteView extends javax.swing.JInternalFrame {

    JDesktopPane parent;
    private ArrayList<Cliente> clientes;
    
    public ClienteView(JDesktopPane desktopPane) {
        initComponents();
        this.parent = desktopPane;
        setClosable(true);
        setTamanhoColunasTabela();
        
        controlarBotoes(0); 
        ClienteDAO cd = new ClienteDAO();
        clientes = (ArrayList) cd.list();
        preencherTabela(clientes);
        
        //preencher campo de data do cadastro automaticamente
        jtfDataCadastro.setText(new SimpleDateFormat("dd/MM/yyyy").format(new Date()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfNomeRSocial = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jtfCpfCnpj = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfEndereco = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtfId = new javax.swing.JTextField();
        jtfFone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtfUsuario = new javax.swing.JTextField();
        jtfSenha = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaObs = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jbServicos = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jtfDataCadastro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jbPesquisa = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Clientes");

        jLabel2.setText("Nome / R.Social:");

        jLabel3.setText("Telefone(s):");

        jLabel4.setText("E-mail:");

        jLabel6.setText("CPF / CNPJ:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Cadastro de Clientes");

        jLabel7.setText("ID:");

        jtfId.setEditable(false);

        jLabel9.setText("Usuário WHM:");

        jLabel10.setText("Senha:");

        jtaObs.setColumns(20);
        jtaObs.setRows(5);
        jScrollPane2.setViewportView(jtaObs);

        jLabel11.setText("Observações:");

        jbServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/servicos.png"))); // NOI18N
        jbServicos.setText("Serviços");
        jbServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbServicosActionPerformed(evt);
            }
        });

        jLabel12.setText("Data Cadastro:");

        jLabel8.setText("Endereço:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfNomeRSocial, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                    .addComponent(jtfEmail))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jtfCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfFone, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jtfEndereco)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfSenha))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jbServicos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfNomeRSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)
                        .addComponent(jtfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome / R.Social", "CPF / CNPJ", "E-mail", "Telefone", "Endereço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jbPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/find.png"))); // NOI18N
        jbPesquisa.setText("Pesquisa");
        jbPesquisa.setAutoscrolls(true);
        jbPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisaActionPerformed(evt);
            }
        });

        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trash.png"))); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jbPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbPesquisa)
                    .addComponent(jbSalvar)
                    .addComponent(jbCancelar)
                    .addComponent(jbExcluir))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 937, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void preencherTabela(ArrayList<Cliente> clientes){
        DefaultTableModel modeloTb = (DefaultTableModel)jTable1.getModel();
        modeloTb.setNumRows(0);
        for(Cliente c : clientes){
            modeloTb.addRow(new Object[]{c.getId(), c.getNomeRSocial(), c.getCpfCnpj(), c.getEmail(), c.getTelefone(), c.getEndereco()});
        }
        /*
        for(int j = 0; j < clientes.size(); j++){
            Cliente c = clientes.get(j);
            modeloTb.addRow(new Object[]{c.getId(), c.getNome(), c.getEmail(), c.getFone(), c.getDtNasc(), c.getRg()});
        }
        */  
    }
    
    private void setTamanhoColunasTabela(){
        jTable1.getColumnModel().getColumn(0).setMaxWidth(35);
        jTable1.getColumnModel().getColumn(1).setMaxWidth(200);
        jTable1.getColumnModel().getColumn(2).setMaxWidth(170);
        jTable1.getColumnModel().getColumn(3).setMaxWidth(200);
        jTable1.getColumnModel().getColumn(4).setMaxWidth(170);
        jTable1.getColumnModel().getColumn(5).setMaxWidth(200);
    }
    
    private void controlarBotoes(int estadoTela){
        switch(estadoTela){
            case 0: //inicial
                jbPesquisa.setEnabled(true);
                jbSalvar.setEnabled(true);
                jbCancelar.setEnabled(false);
                jbExcluir.setEnabled(false);
                break;
            case 1: //edição - com linha da tabela já selecionada
                jbSalvar.setEnabled(true);
                jbCancelar.setEnabled(true);
                jbExcluir.setEnabled(true);
                jbPesquisa.setEnabled(false);
                break;
            case 2: //Selecionou alguma linha da tabela
                jbExcluir.setEnabled(true);

        }
    }
    
    public void limpaCampos(){
        jtfId.setText("");
        jtfNomeRSocial.setText("");
        jtfCpfCnpj.setText("");
        jtfFone.setText("");
        jtfEmail.setText("");
        jtfEndereco.setText("");
        jtfDataCadastro.setText("");
        jtfUsuario.setText("");
        jtfSenha.setText("");
        jtaObs.setText("");
        
    }
    
    public int getIdClienteLinhaTabela(int linha){
        if(linha < 0 || linha > jTable1.getRowCount())
            return 0;
        else{
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            return (int)model.getValueAt(linha, 0); // 0(zero) referente ao primeiro campo (ID) da tabela
        }
    }
    public Cliente getClienteLinhaTabela(int linha){
        if(linha < 0 || linha > jTable1.getRowCount())
            return null;
        
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        Cliente c = new Cliente();
        for(int i=0; i<6; i++){
            switch(i){
                case 0:
                    c.setId((int)model.getValueAt(linha, i));
                    break;
                case 1:
                    c.setNomeRSocial((String)model.getValueAt(linha, i));
                    break;
                case 2:
                    c.setCpfCnpj((String)model.getValueAt(linha, i));
                    break;
                case 3:
                    c.setEmail((String)model.getValueAt(linha, i));
                    break;
                case 4:
                    c.setTelefone((String)model.getValueAt(linha, i));
                    break;
                case 5:
                    c.setEndereco((String)model.getValueAt(linha, i));
                    break;
            }
        }
        return c;
    }
    
    private void jbServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbServicosActionPerformed
        if(!jtfId.getText().equals("")){
            Cliente cli = null;
            for(int i = 0; i < clientes.size(); i++){
                if(clientes.get(i).getId() == Integer.parseInt(jtfId.getText())){
                    cli = clientes.get(i);
                    break;
                }
            }
            ClienteServicosView cs = new ClienteServicosView(super.getDesktopPane(), cli);
            cs.setVisible(true);
            parent.add(cs);
            parent.setComponentZOrder(cs, 0);
            
        }else{
            JOptionPane.showMessageDialog(this, "Selecione algum cliente!", "Serviços por cliente", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jbServicosActionPerformed

    private void jbPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisaActionPerformed
        String nomeRSocial = jtfNomeRSocial.getText();
        DefaultTableModel modeloTb = (DefaultTableModel)jTable1.getModel();
        ClienteDAO cd = new ClienteDAO();
        ArrayList<Cliente> clientes = (ArrayList) cd.consultar(nomeRSocial);
        preencherTabela(clientes);
    }//GEN-LAST:event_jbPesquisaActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        String nome = jtfNomeRSocial.getText().toUpperCase();
        String cpfCnpj = jtfCpfCnpj.getText();
        String email = jtfEmail.getText();
        String fone = jtfFone.getText();
        String endereco = jtfEndereco.getText();

        String dataCadastro = jtfDataCadastro.getText();
        String usuario = jtfUsuario.getText();
        String senha = jtfSenha.getText();
        String obs = jtaObs.getText();

        String id = jtfId.getText();
        if(id.equals("")){ //campo vazio - insert
            Cliente cli = new Cliente(nome, cpfCnpj, email, fone, endereco, dataCadastro, obs, usuario,senha);
            new ClienteDAO().insert(cli);
        }else{ //campo preenchido - update
            Cliente cli = new Cliente(Integer.parseInt(id), nome, cpfCnpj, email, fone, endereco, dataCadastro, obs, usuario,senha);
            new ClienteDAO().update(cli);
        }

        controlarBotoes(0);
        limpaCampos();
        jtfDataCadastro.setText(new SimpleDateFormat("dd/MM/yyyy").format(new Date()));
        
        ClienteDAO cd = new ClienteDAO();
        clientes = (ArrayList) cd.list();
        preencherTabela(clientes);
        
        
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        controlarBotoes(0);
        limpaCampos();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        String id = jtfId.getText();
        if(id.equals(""))
            return;
        if(JOptionPane.showConfirmDialog(this, "Realmente excluir?") == 0){
            ClienteDAO cd = new ClienteDAO();
            cd.delete(Integer.parseInt(id));

            clientes = (ArrayList) cd.list();
            preencherTabela(clientes);
        }

        controlarBotoes(0);
        limpaCampos();
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // pegar a linha selecionada e jogar os dados correspondentes para cima
        // desabilitar botoes: editar e pesquisar - estado atual: edição
        // deixar habilitado: salvar, cancelar e excluir
        int linhaSelecionada = jTable1.getSelectedRow();
        if(linhaSelecionada >= 0){
            controlarBotoes(1);
            int idCliente = getIdClienteLinhaTabela(linhaSelecionada);
            Cliente c = null;
            for(int i = 0; i < clientes.size(); i++){
                if(clientes.get(i).getId() == idCliente){
                    c = clientes.get(i);
                }
            }

            if(c != null){
                jtfId.setText(String.valueOf(c.getId()));
                jtfNomeRSocial.setText(c.getNomeRSocial());
                jtfCpfCnpj.setText(c.getCpfCnpj());
                jtfEmail.setText(c.getEmail());
                jtfFone.setText(c.getTelefone());
                jtfEndereco.setText(c.getEndereco());
                jtfDataCadastro.setText(c.getDataCadastroFromSQL());
                jtfUsuario.setText(c.getUsuario());
                jtfSenha.setText(c.getSenha());
                jtaObs.setText(c.getObservacao());
            }
        }
        boolean excluir = false;
        if(excluir){
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.removeRow(linhaSelecionada);
        }

        // ao carregar a tela, necessário deixar habilitado:
        // pesquisa, salvar (se nome diferente de vazio),
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbPesquisa;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JButton jbServicos;
    private javax.swing.JTextArea jtaObs;
    private javax.swing.JTextField jtfCpfCnpj;
    private javax.swing.JTextField jtfDataCadastro;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfEndereco;
    private javax.swing.JTextField jtfFone;
    private javax.swing.JTextField jtfId;
    private javax.swing.JTextField jtfNomeRSocial;
    private javax.swing.JTextField jtfSenha;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables
}
